modules:
  - compose/cmp-app
  - compose/cmp-shared
  - compose/cmp-wasm
  - jvm/app
  - jvm/data
  - jvm/ktor
  - native/cinterop
  - native/linux
  - native/macos
  - native/windows
  - plugins/build-config
  - plugins/native-image
  - shared
  - web/js
  - web/wasi
  - web/wasm

plugins:
  - //plugins/build-config
  - //plugins/native-image
