modules:
  # - "*-cli"
  - jvm/app
  - jvm/compose
  - jvm/data
  - jvm/ktor
  - native/cinterop
  - native/linux
  - native/macos
  - native/windows
  - plugins/build-config
  - plugins/native-image
  - shared
  - web/js
  - web/wasm
  # - web/wasi

plugins:
  - //plugins/build-config
  - //plugins/native-image
