modules:
  - build-logic/plugins/bcv
  - build-logic/plugins/build-config
  - build-logic/plugins/native-image
  - compose/cmp-app
  - compose/cmp-shared
  - compose/cmp-wasm
  - jvm/app
  - jvm/data
  - jvm/ktor
  - native/cinterop
  - native/linux
  - native/macos
  - native/windows
  - shared
  - web/js
  - web/wasi
  - web/wasm

plugins:
  - //build-logic/plugins/bcv
  - //build-logic/plugins/native-image
  - //build-logic/plugins/build-config
