ktor {
  deployment {
    host = 0.0.0.0
    port = 8080
    port = ${?PORT}
    shutdownGracePeriod = 200
    shutdownTimeout = 200
    // tcpKeepAlive = true
    // (Netty)
    // maxInitialLineLength = 2048
    // maxHeaderSize = 4096
  }

  development = false

  application {
    modules = [AppKt.module]
    // startup = concurrent
    // dependencies = []
  }
}

host = 127.0.0.1
host = ${?HOST}
port = 8080
port = ${?PORT}
environment = DEV
environment = ${?ENVIRONMENT}

plugins {
  otel-extn {
    enabled = true
    traceIdHeader = "X-TraceId"
  }
}